# Generated by Django 5.1.4 on 2024-12-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Compound",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("smiles", models.TextField(blank=True, null=True)),
                (
                    "pdb_file",
                    models.FileField(blank=True, null=True, upload_to="pdb_files/"),
                ),
                (
                    "structure_type",
                    models.CharField(
                        choices=[("SMILES", "SMILES"), ("PDB", "PDB")], max_length=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrugLibrary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("smiles", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("pdb_id", models.CharField(max_length=10)),
            ],
        ),
    ]
