# Generated by Django 5.1.4 on 2024-12-10 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compound",
            name="affinity_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compound",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
