# Generated by Django 5.1.3 on 2025-03-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='validation_status',
        ),
    ]
