# Generated by Django 5.1.3 on 2025-03-12 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_target_validation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedProteinTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdb_structure', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='compound',
            options={},
        ),
        migrations.AlterModelOptions(
            name='screeningjob',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='compound',
            name='app_compoun_type_f3fe79_idx',
        ),
        migrations.RemoveIndex(
            model_name='screeningjob',
            name='app_screeni_status_71304a_idx',
        ),
        migrations.RemoveIndex(
            model_name='screeningjob',
            name='app_screeni_docking_ea77f0_idx',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='alphafold_job_id',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='converted_pdb',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='converted_smiles',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='type',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='validation_errors',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='validation_status',
        ),
        migrations.RemoveField(
            model_name='screeningjob',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='screeningjob',
            name='complex_structure',
        ),
        migrations.RemoveField(
            model_name='screeningjob',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='screeningjob',
            name='ligand_pdbqt',
        ),
        migrations.RemoveField(
            model_name='screeningjob',
            name='similarity_data',
        ),
        migrations.RemoveField(
            model_name='screeningjob',
            name='status',
        ),
        migrations.RemoveField(
            model_name='screeningjob',
            name='visualization_config',
        ),
        migrations.AddField(
            model_name='compound',
            name='data',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compound',
            name='input_type',
            field=models.CharField(default='SMILES', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screeningjob',
            name='pdb_file',
            field=models.FileField(default='pdb_file', upload_to='', verbose_name='pdb<django.db.model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screeningjob',
            name='repurposing_info',
            field=models.JSONField(default={'name': 'Benjamin Watson'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compound',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='screeningjob',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compound'),
        ),
        migrations.AlterField(
            model_name='screeningjob',
            name='docking_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='screeningjob',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.predefinedproteintarget'),
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
