# Generated by Django 5.1.4 on 2024-12-19 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job_knowndrug_delete_druglibrary_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compound',
        ),
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.RemoveField(
            model_name='knowndrug',
            name='tanimoto_score',
        ),
        migrations.AddField(
            model_name='job',
            name='results_binding_pose_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='knowndrug',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='pdb_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowndrug',
            name='smiles',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='target',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
