# Generated by Django 5.1.3 on 2025-03-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_predefinedproteintarget_alter_compound_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningjob',
            name='docking_score',
        ),
        migrations.AddField(
            model_name='predefinedproteintarget',
            name='description',
            field=models.TextField(default='Desription unavailable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screeningjob',
            name='docking_info',
            field=models.JSONField(default='Docking info unavailable'),
            preserve_default=False,
        ),
    ]
