# Generated by Django 5.1.3 on 2025-03-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_screeningjob_docking_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predefinedproteintarget',
            name='pdb_structure',
        ),
        migrations.AddField(
            model_name='predefinedproteintarget',
            name='pdb_file',
            field=models.FileField(default='nofile.pdb', upload_to='pdb_files/'),
            preserve_default=False,
        ),
    ]
